/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tablas;


import Conexion.conexion;
import static Tablas.Login.idUsuarioLogueado;
import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.io.File;
import javafx.scene.Scene;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javax.swing.GroupLayout.Group;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import com.mysql.jdbc.Connection;

import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame {
Conexion.conexion con = new conexion();
Connection cn = con.conectar();
public static int idUsuarioLogueado; // Declara esto al inicio de la clase

    public Login() {
        initComponents();
        
                          setSize(690, 489);  // ancho, alto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        fon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        caja2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        caja3 = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        ver = new javax.swing.JLabel();
        ocultar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Shotify");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(30, 140, 220, 69);
        jPanel3.add(logo);
        logo.setBounds(70, 240, 150, 130);

        fon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.reproductor.jpg"))); // NOI18N
        jPanel3.add(fon);
        fon.setBounds(0, 0, 300, 490);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 300, 490);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 17)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(30, 150, 82, 47);

        caja2.setBorder(null);
        caja2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                caja2MousePressed(evt);
            }
        });
        caja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja2ActionPerformed(evt);
            }
        });
        jPanel4.add(caja2);
        caja2.setBounds(110, 160, 230, 16);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator2);
        jSeparator2.setBounds(110, 180, 235, 10);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 17)); // NOI18N
        jLabel4.setText("Contraseña:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(30, 210, 110, 30);

        caja3.setBorder(null);
        caja3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                caja3MousePressed(evt);
            }
        });
        caja3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja3ActionPerformed(evt);
            }
        });
        jPanel4.add(caja3);
        caja3.setBounds(140, 210, 200, 16);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator4);
        jSeparator4.setBounds(140, 230, 204, 20);

        ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/view_12639261.png"))); // NOI18N
        ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verMouseClicked(evt);
            }
        });
        jPanel4.add(ver);
        ver.setBounds(160, 250, 40, 37);

        ocultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hide_12639180.png"))); // NOI18N
        ocultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultarMouseClicked(evt);
            }
        });
        jPanel4.add(ocultar);
        ocultar.setBounds(160, 250, 40, 37);

        jLabel5.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 3, 36)); // NOI18N
        jLabel5.setText("Inicia Sesion");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(50, 80, 277, 51);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/switch_5949781.png"))); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(120, 350, 150, 90);

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(850, 0, 70, 70);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove_10867871.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(340, 0, 40, 50);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("New User?");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(40, 310, 70, 16);

        jLabel10.setFont(new java.awt.Font("Bauhaus 93", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText(" CREATE USER");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel10);
        jLabel10.setBounds(110, 310, 90, 20);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Change password ");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(220, 310, 120, 16);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(300, 0, 380, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caja2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caja2MousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_caja2MousePressed

    private void caja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja2ActionPerformed

    private void caja3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caja3MousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_caja3MousePressed

    private void caja3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja3ActionPerformed

    private void verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMouseClicked
        ver.setVisible(false);
        ocultar.setVisible(true);
        caja3.setEchoChar((char)0);
        // TODO add your handling code here:
    }//GEN-LAST:event_verMouseClicked

    private void ocultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultarMouseClicked
        ver.setVisible(true);
        ocultar.setVisible(false);
        caja3.setEchoChar('*');

        // TODO add your handling code here:
    }//GEN-LAST:event_ocultarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Obtenemos los datos de tus JTextFields
    String user = caja2.getText(); // Ajusta al nombre real de tu variable
    String pass = caja3.getText(); 

    // 2. Validación de campos vacíos
    if (user.isEmpty() || pass.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "POR FAVOR, INGRESE SU USUARIO Y CONTRASEÑA");
    } else {
        try {
            // 3. Conexión usando tu clase del paquete Conexion
            Conexion.conexion cc = new Conexion.conexion();
            java.sql.Connection cn = cc.conectar();

            // 4. Consulta SQL para buscar al usuario
            // Buscamos que coincidan NOMBRE y CONTRASEÑA exactamente
            String sql = "SELECT * FROM usuarios WHERE NOMBRE = ? AND CONTRASEÑA = ?";

            java.sql.PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, user);
            ps.setString(2, pass);

            java.sql.ResultSet rs = ps.executeQuery();

            // 5. Verificar si se encontró el usuario
            if (rs.next()) {
                javax.swing.JOptionPane.showMessageDialog(null, "¡BIENVENIDO AL SISTEMA!");
                idUsuarioLogueado = rs.getInt("ID_USUARIO");

                // Abrir el reproductor principal (ReproductorCoreUI)
                ReproductorCoreUI principal = new ReproductorCoreUI();
                principal.setVisible(true);
                
                // Cerrar la ventana de login
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "USUARIO O CONTRASEÑA INCORRECTOS");
                // Limpiar contraseña para reintentar
                caja3.setText("");
            }

            cn.close();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "ERROR EN EL LOGIN: " + e.getMessage());
        }
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Registro j=new Registro();
        j.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caja1;
    private javax.swing.JTextField caja2;
    private javax.swing.JPasswordField caja3;
    private javax.swing.JLabel fon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel ocultar;
    private javax.swing.JLabel ver;
    // End of variables declaration//GEN-END:variables
}
