/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tablas;

import Conexion.conexion;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.sql.PreparedStatement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class Registro extends javax.swing.JFrame {
Conexion.conexion con = new conexion();
Connection cn = con.conectar();
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        contraseña = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        fonre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registro");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 20, 170, 51);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        nombre.setBorder(null);
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreMousePressed(evt);
            }
        });
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel2.add(nombre);
        nombre.setBounds(270, 140, 220, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 17)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(170, 140, 70, 30);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(270, 160, 220, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 17)); // NOI18N
        jLabel5.setText("Email");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(170, 170, 60, 30);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(270, 190, 220, 10);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 17)); // NOI18N
        jLabel6.setText("Contraseña");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(160, 200, 100, 30);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(270, 220, 220, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 17)); // NOI18N
        jLabel9.setText("Genero");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(170, 230, 110, 30);

        email.setBorder(null);
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailMousePressed(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email);
        email.setBounds(270, 170, 220, 16);

        contraseña.setBorder(null);
        contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraseñaMousePressed(evt);
            }
        });
        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(contraseña);
        contraseña.setBounds(270, 200, 220, 16);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add-user (1).png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(500, 240, 100, 90);
        jPanel2.add(logo);
        logo.setBounds(480, 10, 150, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/profile_15484694.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 140, 70, 70);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(270, 230, 170, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(50, 90, 640, 370);

        fonre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.reproductor.jpg"))); // NOI18N
        jPanel1.add(fonre);
        fonre.setBounds(0, 0, 740, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMousePressed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMousePressed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void contraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaMousePressed

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Obtener datos de los componentes
    String nom = nombre.getText();
    String gmail = email.getText();
    String con = contraseña.getText();
    // Obtener el género seleccionado del ComboBox
    String gen = jComboBox1.getSelectedItem().toString();

    // 2. Validación de campos vacíos
    if (nom.isEmpty() || gmail.isEmpty() || con.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "DEBE COMPLETAR TODOS LOS DATOS");
    } else {
        try {
            // 3. Conexión usando tu clase
            Conexion.conexion cc = new Conexion.conexion();
            java.sql.Connection cn = cc.conectar();

            // 4. Consulta SQL ajustada a tu tabla 'usuarios'
            // Nota: ID_USUARIO es auto-incremental, no se incluye.
            String consulta = "INSERT INTO usuarios (NOMBRE, GMAIL, CONTRASEÑA, GENERO) VALUES (?, ?, ?, ?)";

            java.sql.PreparedStatement ps = cn.prepareStatement(consulta);
            ps.setString(1, nom);
            ps.setString(2, gmail);
            ps.setString(3, con);
            ps.setString(4, gen);

            // 5. Ejecutar y verificar
            int resultado = ps.executeUpdate();

            if (resultado > 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "DATOS GUARDADOS CON ÉXITO");
                
                // Limpiar campos después de guardar
                nombre.setText("");
                email.setText("");
                contraseña.setText("");
                jComboBox1.setSelectedIndex(0);

                // Abrir menú y cerrar registro
                Login pg = new Login();
                pg.setVisible(true);
                dispose();
            }

            cn.close();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contraseña;
    private javax.swing.JTextField email;
    private javax.swing.JLabel fonre;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
